### ISSUE TITLE
[Feature Request] Process Folders (Batch / Bulk)

### ISSUE THREAD

**Issue by RoyiAvital** [kynan/nbstripout#162] opened 2021-12-01 09:02 UTC
It would be great to have an option to process folders (With recursive option as well) and a batch of file with some RegExp like string (Like `MyNotes*.ipynb`).

Something like:

```
nbstripout -d <pathToDir>
```

Will process all files in that folder.

```
nbstripout -d -r <pathToDir>
```

Will process all files in the folder and sub folders.

**Comment by kynan** [comment] 2022-01-02 20:32
This is a duplicate of #127 and my answer is the same: I'm not going to implement this as you can trivially achieve this as a shell one-liner like
```shell
find . -name *.ipynb -exec nbstripout {} +
```

If you can't live without this you're welcome to have a go at implementing it, but I won't promise I'll merge it as I think it it's entirely unnecessary. See [this comment](https://github.com/kynan/nbstripout/issues/127#issuecomment-818075365) on why it won't be trivial.

**Closed** 2022-08-01 20:18 UTC
Labels: resolution:duplicate, type:enhancement
