### ISSUE TITLE
uninstall fails

### ISSUE THREAD

**Issue by michaelaye** [kynan/nbstripout#43] opened 2016-12-10 23:33 UTC
v: 0.2.8 from pip
Python 3.5 using most recent miniconda on Mac 10.11.6

(stable) └─❱❱❱ nbstripout --uninstall                                  +5357 16:31 ❰─┘
Traceback (most recent call last):
  File "/Users/klay6683/miniconda3/envs/stable/bin/nbstripout", line 11, in <module>
    sys.exit(main())
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/nbstripout.py", line 248, in main
    sys.exit(uninstall(args.attributes))
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/nbstripout.py", line 191, in uninstall
    f.write(''.join(lines))
ValueError: I/O operation on closed file.

**Comment by kynan** [comment] 2016-12-11 14:57
Duplicate of #40. Please update to 0.2.9 where this issue is fixed.

**Closed by kynan** 2016-12-11 14:57 UTC
